services:
  app:
    build: .
    container_name: chedice
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
      - model-cache:/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: never

volumes:
  model-cache:
